# Generated by Django 4.2.2 on 2023-06-14 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Категории контента',
                'verbose_name_plural': 'Категории контента',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('titlex', models.CharField(max_length=50, verbose_name='Заголовок 2')),
                ('content', models.TextField(blank=True, verbose_name='Сатья')),
                ('photo_b', models.ImageField(upload_to='content/photos_big/%Y/%m/%d/')),
                ('photo_l', models.ImageField(upload_to='content/photos_large/%Y/%m/%d/')),
                ('photo_s', models.ImageField(upload_to='content/photos_small/%Y/%m/%d/')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_published', models.BooleanField(default=True, verbose_name='Публикация')),
                ('url', models.URLField(blank=True, verbose_name='ссылка')),
                ('cat', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='BiBcar.categorycontent')),
            ],
            options={
                'verbose_name': 'Контент',
                'verbose_name_plural': 'Контент',
                'ordering': ['time_create', 'title'],
            },
        ),
    ]
