# Generated by Django 4.2.2 on 2023-06-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BiBcar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='photo_b',
            field=models.ImageField(blank=True, upload_to='content/photos_big/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='photo_l',
            field=models.ImageField(blank=True, upload_to='content/photos_large/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='content',
            name='photo_s',
            field=models.ImageField(blank=True, upload_to='content/photos_small/%Y/%m/%d/'),
        ),
    ]
